name: Spam Classification Inference

on:
  workflow_dispatch:
    inputs:
      input_text:
        description: "Message to classify as Ham or Spam"
        required: true
        type: string

permissions:
  contents: read
  packages: read

env:
  IMAGE_NAME: ghcr.io/g25ait2032-prog/mlops_group-inference:latest
  HF_MODEL: nagaananth/MLOPS_group-v2

jobs:
  inference:
    runs-on: ubuntu-latest

    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image
        run: docker pull ${{ env.IMAGE_NAME }}

      - name: Run inference
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN_gr }}
          INPUT_TEXT: ${{ github.event.inputs.input_text }}
        run: |
          docker run --rm \
            -e HF_TOKEN \
            -e HF_MODEL="${{ env.HF_MODEL }}" \
            -e INPUT_TEXT \
            ${{ env.IMAGE_NAME }}
